const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];let activeFilter='all',observer;
function countryLabel(a){return a.country==='brasil'?'🇧🇷 Brasil':a.country==='mexico'?'🇲🇽 México':'🎨 Produção artística'}
function card(a){let c=countryLabel(a);return `<article class="activity-card reveal" data-country="${a.country}"><div class="activity-cover" style="background-image:url('assets/atividades/${a.cover}')"><span class="activity-country">${c}</span></div><div class="activity-body"><span class="activity-number">${String(a.id).padStart(2,'0')} · ${a.country==='brasil'?'Brasil':a.country==='mexico'?'México':'Arte'}</span><h3>${a.title}</h3><p>${a.what}</p><div class="activity-meta"><span><i class="fa-solid ${a.icon}"></i> ${a.subtitle}</span><button class="details-btn" data-id="${a.id}">Ver detalhes</button></div></div></article>`}
function renderActivities(){let term=($('#activitySearch').value||'').trim().toLowerCase();let list=activities.filter(a=>(activeFilter==='all'||a.country===activeFilter)&&(a.title+' '+a.subtitle+' '+a.what).toLowerCase().includes(term));$('#activityGrid').innerHTML=list.map(card).join('');$('#emptyState').hidden=!!list.length;observeReveals()}
function renderExperiences(){$('#experienceGrid').innerHTML=experiences.map(e=>`<article class="experience-card reveal"><div class="experience-icon"><i class="fa-solid ${e.icon}"></i></div><h3>${e.activity}</h3><p>${e.text}</p></article>`).join('')}
function renderGallery(){let p=[];for(let i=1;i<=31;i++)p.push({src:`assets/atividades/brasil-mexico-${String(i).padStart(2,'0')}.webp`,label:`Página ${i} do PDF principal`});p.push({src:'assets/atividades/argolas-1.webp',label:'Jogo de argolas — página 1'},{src:'assets/atividades/argolas-2.webp',label:'Jogo de argolas — página 2'});$('#sourceGallery').innerHTML=p.map(x=>`<button class="gallery-item" data-src="${x.src}" data-label="${x.label}"><img loading="lazy" decoding="async" src="${x.src}" alt="${x.label}"></button>`).join('')}
function openModal(html){let d=$('#activityModal');$('#modalContent').innerHTML=html;d.showModal?d.showModal():d.setAttribute('open','')}
function openActivity(id){let a=activities.find(x=>x.id===+id);if(!a)return;openModal(`<div class="modal-inner"><div class="modal-title"><span class="activity-number">${String(a.id).padStart(2,'0')} · ${countryLabel(a)}</span><h2>${a.title}</h2><p>${a.subtitle}</p></div><div class="modal-columns"><div class="modal-block"><h4>💡 O que é?</h4><p>${a.what}</p></div><div class="modal-block"><h4>⚙️ Do que é feito?</h4><p>${a.made}</p></div><div class="modal-block"><h4>🏃 Como se brinca?</h4><p>${a.how}</p></div><div class="modal-block"><h4>❤️ Importância cultural${a.id===17?' e pedagógica':''}</h4><p>${a.importance}</p></div>${a.experience?`<div class="modal-block"><h4>👧 Nossa experiência – Infantil 1</h4><p>${a.experience}</p></div>`:''}</div><div class="modal-source-pages">${a.pages.map(p=>`<img loading="lazy" src="assets/atividades/${p}" alt="Página do material sobre ${a.title}">`).join('')}</div></div>`)}
function setup(){let nav=$('#navLinks'),toggle=$('#navToggle');toggle.onclick=()=>{let o=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',o);toggle.innerHTML=o?'<i class="fa-solid fa-xmark"></i>':'<i class="fa-solid fa-bars"></i>'};$$('#navLinks a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
let key='brincando-theme',saved=localStorage.getItem(key);if(saved==='dark')document.body.classList.add('dark');let tb=$('#themeToggle'),theme=()=>tb.innerHTML=document.body.classList.contains('dark')?'<i class="fa-solid fa-sun"></i>':'<i class="fa-solid fa-moon"></i>';theme();tb.onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem(key,document.body.classList.contains('dark')?'dark':'light');theme()};
let back=$('#backTop'),scroll=()=>{let h=document.documentElement.scrollHeight-innerHeight;$('#progressBar').style.width=`${h?(scrollY/h)*100:0}%`;back.classList.toggle('show',scrollY>500)};addEventListener('scroll',scroll,{passive:true});scroll();back.onclick=()=>scrollTo({top:0,behavior:'smooth'});
$$('.filter-btn').forEach(b=>b.onclick=()=>{$$('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderActivities()});$('#activitySearch').oninput=renderActivities;
$('#modalClose').onclick=()=>$('#activityModal').close();$('#activityModal').onclick=e=>{if(e.target===$('#activityModal'))$('#activityModal').close()};document.addEventListener('click',e=>{let b=e.target.closest('.details-btn');if(b)openActivity(b.dataset.id);let g=e.target.closest('.gallery-item');if(g)openModal(`<div class="modal-inner"><div class="modal-title"><span class="activity-number">Material original</span><h2>${g.dataset.label}</h2><p>Página incorporada a partir dos PDFs enviados para a Feira Cultural.</p></div><img style="width:100%;border-radius:18px;border:1px solid var(--line)" src="${g.dataset.src}" alt="${g.dataset.label}"></div>`)})}
function observeReveals(){if(!observer)observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});$$('.reveal:not(.visible)').forEach(e=>observer.observe(e))}
document.addEventListener('DOMContentLoaded',()=>{$('#year').textContent=new Date().getFullYear();renderActivities();renderExperiences();renderGallery();setup();observeReveals()});
